
name: CloudFront Invalidation

on:
  workflow_run:
    workflows: ["Deploy to S3"]
    types:
      - completed

jobs:
  invalidate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
    
    - name: Create CloudFront invalidation
      run: |
        echo "Creating CloudFront invalidation for distribution ABC123"
        aws cloudfront create-invalidation --distribution-id ABC123 --paths "/*"
        echo "CloudFront invalidation created successfully"
